[build-system]
requires = ["setuptools", "setuptools-scm", "numpy>=2.1.0",]
build-backend = "setuptools.build_meta"

[project]
name = "monty"
maintainers = [
    { name = "Shyue Ping Ong", email = "ongsp@ucsd.edu" },
]
description = "Monty is the missing complement to Python."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [

]
version = "2024.7.30"

[project.optional-dependencies]
ci = [
    "pytest>=8",
    "pytest-cov>=4",
    "coverage",
    "numpy<2.0.0",
    "ruamel.yaml",
    "msgpack",
    "tqdm",
    "pymongo",
    "pandas",
    "pint",
    "orjson",
    "types-orjson",
    "types-requests",
    "torch"
]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["monty"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = [
    "@deprecated",
    "def __repr__",
    "if 0:",
    "if __name__ == .__main__.:",
    "if self.debug:",
    "if settings.DEBUG",
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "show_plot",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
    "except ImportError:"
]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
lint.select = [
  "I",  #isort
]

lint.isort.required-imports = ["from __future__ import annotations"]
